import Head from "next/head";
import { ReactNode } from "react";
import Navbar from "../navbar";

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Blog with GraphQL</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <div className={`w-full h-screen`}>
        <Navbar />
        <main className="">{children}</main>
      </div>
    </>
  );
}
